### ISSUE TITLE
有谁自己改的Guix 支持从备用页面下载源码了吗?

### ISSUE THREAD

**Issue by nniixxoossccnn** [guix-china/help#3]
意思是:

Guix 官方指定软件包的源码网站在国内过于慢了，用户自己指定一个页面比如: gentoo的distfiles,pkgsrc的distfiles。Guix 优先尝试从这些页面下载。

就像
buildroot 中的backup_site功能
或者gentoo的distfiles
pkgsr的BACKUP_SITE

如果有人做到的话，可以发出来参考一下吗?

我看着Guix的源码实在无从下手

**Comment by pmeiyu** [comment]
Guix中国镜像（mirror.guix.org.cn）已经上线。见：https://guix-china.github.io/blog/guix-china-mirror-is-online-now/

**Comment by ghost** [comment]
这个功能还没实现，需要修改 `guix/download.scm` 里的 `%mirrors` ，以支持自定义配置，建议去官方邮件列表和 irc 讨论。

https://git.savannah.gnu.org/cgit/guix.git/tree/guix/download.scm#n50
