### ISSUE TITLE
https://guix.gnu.org/packages/ 有国内镜像吗

### ISSUE THREAD

**Issue by QiangF** [guix-china/help#9]

**Comment by pmeiyu** [comment]
这只是一个搜索软件包的网页。你为什么想要镜像呢？从国内访问速度很慢吗？

**Comment by QiangF** [comment]
https://guix.gnu.org/packages/ 列出的软件， 有国内镜像吗

**Comment by QiangF** [comment]
guixd的软件仓库有镜像了吗

**Comment by pmeiyu** [comment]
我们已经提供Git镜像和Substitute镜像。具体信息见：https://guix-china.github.io/wiki/mirror/

**Comment by QiangF** [comment]
你是说guix这个管理器的镜像嘛，我是说比如我要装emacs，国内有guix中的emacs软件包的镜像吗

**Comment by QiangF** [comment]
我的意思是这个 https://github.com/ustclug/mirrorrequest/issues/96

**Comment by QiangF** [comment]
光guix没其他软件怎么万嘛

**Comment by pmeiyu** [comment]
> 你是说guix这个管理器的镜像嘛，我是说比如我要装emacs，国内有guix中的emacs软件包的镜像吗

> 我的意思是这个 [ustclug/mirrorrequest#96](https://github.com/ustclug/mirrorrequest/issues/96)

> 光guix没其他软件怎么万嘛

上述「Substitute镜像」就是「构建好的二进制软件包的镜像」，即通常发行版所谓的「软件源」。Guix和Debian、Arch Linux等发行版的差异很大，你需要阅读文档了解一下Guix里的相关概念和镜像的使用方法。

**Comment by QiangF** [comment]
哦 谢谢！
